/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_aiwac_service_AiwacFaceDetectService */

#ifndef _Included_com_aiwac_service_AiwacFaceDetectService
#define _Included_com_aiwac_service_AiwacFaceDetectService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_aiwac_service_AiwacFaceDetectService
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_aiwac_service_AiwacFaceDetectService_init
  (JNIEnv *, jclass);

/*
 * Class:     com_aiwac_service_AiwacFaceDetectService
 * Method:    detectFace
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_aiwac_service_AiwacFaceDetectService_detectFace
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
